config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :articles
  get '/articles' => 'articles#index'
  get '/articles/new' => 'articles#new', as: 'new_article'
  post '/articles' => 'articles#create', as: 'create_article'
  get '/articles/:id' => 'articles#show', as: 'show_article'
  get '/articles/:id/edit' => 'articles#edit', as: 'edit_article'
  patch '/articles/:id/update' => 'articles#update', as: 'update_article'
  delete '/articles/:id/delete' => 'articles#delete', as: 'delete_article'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :name, presence: true
    validates :body, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)

        if @article.save
            redirect_to articles_path
        else
            render :new
        end
    end

    def edit
        @article = Article.find(params[:id])
    end
  
    def update
      @article = Article.find(params[:id])
  
        if @article.update(article_params)
            redirect_to articles_path
        else
            render :edit
        end
    end

    def delete
        @article = Article.find(params[:id])  
        if @article.destroy
            redirect_to articles_path
        else
            render :edit
        end
    end

    private
    def article_params
       params.require(:article).permit(:name, :body) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/views/articles/edit.html.erb
<%= form_with scope: :article, url: update_article_path, local: true, method: :patch do |f|  %>
  <p>
    <% if @article.errors.any?  %>
      <ul>
        <% @article.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
    <% end %>     
  </p>

        <div class="form">
        <form name="loginform">
            <div class="task">Edit Article</div>
            <div>
                <%= f.label :name %> <br>
                <%= f.text_field :name, :class => 'name' %>
            </div>
            <div>
                <%= f.label :body %><br>
                <%= f.text_area :body, :class  => 'text-field' %>
            </div>
            <div>
                <%= f.submit "Save", :class => 'submit' %>
            </div>
        </form>
          <%=  link_to 'Back to Articles', articles_path, :class => 'index' %>
        </button>
    </div>
<% end %>

app/views/articles/index.html.erb
<div 
    class="app_name">Simple CRUD App | Ruby on Rails</div>                                                                                   
<div class="article-item">
    <table class="table_heads">
        <thead >
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Body</th>
                <th>Actions</th>
            </tr>
        </thead>

        <tbody>
        <% @articles.each do |article| %>
            <tr>
                    <td><%= article.id %></td>
                    <td><%= article.name %></td>
                    <td><%= article.body %></td>
                    <td class="no_line"> 
                    <%= link_to 'Edit', edit_article_path(article.id) %>
                    |
                    <%= link_to 'Delete', delete_article_path(article.id), method: :delete, data: {confirm: "Are you sure?"} %>
                    </td>
            </tr>
        <% end %>
        </tbody>    
    </table>
</div>
 
<%= link_to "New Article", new_article_path, class: 'button' %>

app/views/articles/new.html.erb
<%= form_with scope: :article, url: create_article_path, local: true do |f| %>
    <p>
        <% if @article.errors.any? %>
            <ul>
                <% @article.errors.full_messages.each do |message| %>
                    <li>
                        <%= message %>
                    </li>
                <% end %>
            </ul> 
        <% end %>
    </p>
    <p> 
        <%= f.label :name %>
        <%= f.text_field :name %>
    </p>
    <p>
        <%= f.label :body %>
        <%= f.text_area :body %>
    </p>
    <p>
        <%= f.submit %>
    </p>
    <%= link_to 'Back to articles', articles_path %>
<% end %>

app/views/articles/show.html.erb
<h2>
  <%= @article.name %>
</h2>
<p>
  <%= @article.body %>
</p>

<%= link_to 'Edit', edit_article_path(@article.id) %>
<%= link_to 'Back to Articles', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>